using Nd30.DocumentEngine.Parsing;using Nd30.DocumentEngine.Safety;using Nd30.DocumentEngine.Package;using Nd30.DocumentEngine.Formatting;using Nd30.DocumentEngine.Model;using Xunit;using DocumentFormat.OpenXml.Packaging;using DocumentFormat.OpenXml.Validation;
namespace Nd30.DocumentEngine.Tests;
public class DocumentEngineTests {
 static string F(string n)=>Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../../fixtures/docx",n));static DocumentModel D(string n)=>new DocxParser().Parse(F(n)).Document!;
 [Fact]public void Simple_parser_reads_text(){Assert.Equal("Hello",D("01-simple.docx").Paragraphs[0].Runs[0].Text);}
 [Fact]public void Paragraph_style_is_canonical(){Assert.Equal("Body",D("02-paragraph-style.docx").Paragraphs[0].StyleId);Assert.True(D("02-paragraph-style.docx").Styles.Styles.ContainsKey("Body"));}
 [Fact]public void BasedOn_and_run_style_are_parsed(){var d=D("03-inherited-style.docx");Assert.Equal("Base",d.Styles.Styles["Child"].BasedOn);Assert.Equal("Emphasis",d.Paragraphs[0].Runs[0].StyleId);}
 [Fact]public void Resolver_cascades_defaults_inheritance_styles_and_direct(){var d=D("04-direct-override.docx");var e=new EffectiveFormattingResolver().Resolve(d,d.Paragraphs[0],d.Paragraphs[0].Runs[0]);Assert.Equal(16,e.FontSizePt.Value);Assert.False(e.Bold.Value);Assert.Equal("direct-formatting",e.Bold.Provenance);Assert.Equal("Times New Roman",e.FontFamily.Value);Assert.Equal("document-default",e.FontFamily.Provenance);}
 [Fact]public void Resolver_reports_style_cycle(){var d=D("19-style-cycle.docx");Assert.Throws<StyleInheritanceCycleException>(()=>new EffectiveFormattingResolver().Resolve(d,d.Paragraphs[0],d.Paragraphs[0].Runs[0]));}
 [Fact]public void OnOff_semantics_are_exact(){var d=D("18-onoff-semantics.docx");var b=d.Paragraphs.Select(x=>x.Runs[0].DirectFormatting.Bold).ToArray();Assert.Equal(new bool?[]{null,true,true,true,false,false},b);var i=d.Paragraphs.Select(x=>x.Runs[0].DirectFormatting.Italic).ToArray();Assert.Equal(new bool?[]{null,true,true,true,false,false},i);}
 [Fact]public void Table_cells_are_semantic(){var d=D("07-table.docx");Assert.Equal(2,d.Tables[0].Rows[0].Cells.Count);Assert.Equal("Cell B",d.Tables[0].Rows[0].Cells[1].Paragraphs[0].Runs[0].Text);}
 [Fact]public void Numbering_baseline_is_semantic(){var d=D("17-numbering.docx");Assert.Equal("42",d.Paragraphs[0].NumberingId);Assert.Equal(1,d.Paragraphs[0].NumberingLevel);Assert.Equal("10",d.Numbering.Instances.Single().AbstractNumberId);var l=d.Numbering.AbstractNumbers.Single().Levels[1];Assert.Equal("lowerLetter",l.NumberFormat);Assert.Equal("%2)",l.LevelText);Assert.Equal(1,l.StartValue);}
 [Fact]public void Sections_preserve_boundaries_sizes_and_margins(){var d=D("05-multi-section.docx");Assert.Equal(2,d.Sections.Count);Assert.Equal("p1",d.Sections[0].BoundaryParagraphId);Assert.Equal((uint)1000,d.Sections[0].MarginTopTwips);Assert.Equal((uint)800,d.Sections[0].MarginRightTwips);Assert.Equal((uint)1100,d.Sections[0].MarginBottomTwips);Assert.Equal((uint)1600,d.Sections[0].MarginLeftTwips);Assert.Equal((uint)12240,d.Sections[1].PageWidthTwips);Assert.Equal((uint)1700,d.Sections[1].MarginLeftTwips);}
 [Fact]public void Landscape_section_is_not_flattened(){var d=D("06-landscape-section.docx");Assert.Equal(2,d.Sections.Count);Assert.Equal("landscape",d.Sections[0].Orientation,StringComparer.OrdinalIgnoreCase);Assert.Equal((uint)16838,d.Sections[0].PageWidthTwips);Assert.Equal((uint)1500,d.Sections[0].MarginLeftTwips);Assert.Equal("portrait",d.Sections[1].Orientation,StringComparer.OrdinalIgnoreCase);}
 [Fact]public void Header_footer_links_keep_default_first_even(){var d=D("08-header-footer.docx");Assert.Equal(3,d.Headers.Count);Assert.Equal(3,d.Footers.Count);var s=d.Sections.Single();Assert.Equal(new[]{HeaderFooterKind.Default,HeaderFooterKind.First,HeaderFooterKind.Even},s.HeaderReferences.Select(x=>x.Kind));Assert.All(s.HeaderReferences,x=>Assert.Contains(d.Headers,h=>h.RelationshipId==x.RelationshipId));Assert.All(s.FooterReferences,x=>Assert.Contains(d.Footers,f=>f.RelationshipId==x.RelationshipId));}
 [Fact]public void Complex_PAGE_and_simple_NUMPAGES_with_results(){var d=D("09-page-numbering.docx");var f=d.Paragraphs.SelectMany(x=>x.Fields).ToList();Assert.Contains(f,x=>x.FieldType==FieldType.Page&&x.Result=="3"&&x.SourceRunIds.Count>0);Assert.Contains(f,x=>x.FieldType==FieldType.NumPages&&x.Result=="9");}
 [Fact]public void Readonly_parts_are_detected(){var d=D("16-readonly-parts.docx");Assert.Contains("footnotes",d.ReadOnlyParts);Assert.Contains("endnotes",d.ReadOnlyParts);Assert.Contains("comments",d.ReadOnlyParts);}
 [Theory][InlineData("10-tracked-changes.docx",PatchPolicy.AUDIT_ONLY)][InlineData("11-protected.docx",PatchPolicy.AUDIT_ONLY)][InlineData("12-macro-enabled.docm",PatchPolicy.AUDIT_ONLY)][InlineData("13-ole-embedded.docx",PatchPolicy.AUDIT_ONLY)][InlineData("14-external-relationship.docx",PatchPolicy.GUARDED)][InlineData("15-signed-structure-simulation.docx",PatchPolicy.AUDIT_ONLY)]public void Safety_policy_is_conservative(string f,PatchPolicy p){Assert.Equal(p,PackageSafetyPreflight.Inspect(F(f)).PatchPolicy);}
 [Fact]public void Signed_structure_is_detected_without_crypto_claim(){var s=PackageSafetyPreflight.Inspect(F("15-signed-structure-simulation.docx"));Assert.True(s.IsSigned);Assert.Equal(PatchPolicy.AUDIT_ONLY,s.PatchPolicy);Assert.Contains(s.Diagnostics,x=>x.Code=="SIGNED_PACKAGE"&&x.Message.Contains("not verified"));}
 [Fact]public void Unreadable_package_is_prohibited(){var x=Path.GetTempFileName();File.WriteAllText(x,"not zip");var s=PackageSafetyPreflight.Inspect(x);Assert.False(s.IsReadable);Assert.Equal(PatchPolicy.PROHIBITED,s.PatchPolicy);File.Delete(x);}
 [Theory][InlineData("10-tracked-changes.docx","word/document.xml")][InlineData("12-macro-enabled.docm","word/vbaProject.bin")][InlineData("13-ole-embedded.docx","word/embeddings/oleObject1.bin")][InlineData("08-header-footer.docx","word/header1.xml")][InlineData("16-readonly-parts.docx","word/comments.xml")]public void Full_read_preflight_parse_copy_preserves_bytes_and_critical_parts(string f,string critical){var src=F(f);var before=PackagePreserver.Sha256(src);var inv=PackagePreserver.PartInventory(src);var safety=PackageSafetyPreflight.Inspect(src);Assert.True(safety.IsReadable);Assert.NotNull(new DocxParser().Parse(src).Document);Assert.Equal(before,PackagePreserver.Sha256(src));var dst=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+Path.GetExtension(src));PackagePreserver.CopyWithoutMutation(src,dst);Assert.Equal(before,PackagePreserver.Sha256(dst));Assert.Equal(inv,PackagePreserver.PartInventory(dst));Assert.Contains(critical,PackagePreserver.PartInventory(dst));File.Delete(dst);}
 [Fact]public void OpenXmlValidator_accepts_expected_valid_fixtures(){var excluded=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"15-signed-structure-simulation.docx"};foreach(var f in Directory.GetFiles(Path.GetDirectoryName(F("01-simple.docx"))!).Where(x=>x.EndsWith(".docx")||x.EndsWith(".docm"))){if(excluded.Contains(Path.GetFileName(f)))continue;using var d=WordprocessingDocument.Open(f,false);var errors=new OpenXmlValidator().Validate(d).ToList();Assert.True(errors.Count==0,$"{Path.GetFileName(f)}: "+string.Join(" | ",errors.Select(e=>e.Description)));}}
 [Fact]public void Line_spacing_preserves_rule_units_raw_and_provenance(){var d=D("20-line-spacing.docx");var r=new EffectiveFormattingResolver();var e=d.Paragraphs.Select(p=>r.Resolve(d,p,p.Runs[0]).LineSpacing).ToList();Assert.Equal(1.0,e[0].Value!.Lines);Assert.Equal(1.15,e[1].Value!.Lines,2);Assert.Equal(1.5,e[2].Value!.Lines);Assert.Equal(12,e[3].Value!.Points);Assert.Equal(LineSpacingRule.Exact,e[3].Value!.Rule);Assert.Equal(14,e[4].Value!.Points);Assert.Equal(LineSpacingRule.AtLeast,e[4].Value!.Rule);Assert.Equal("276",e[5].Value!.RawValue);Assert.Contains("style",e[5].Provenance);Assert.Equal(1.5,e[6].Value!.Lines);Assert.Equal("direct-formatting",e[6].Provenance);}
 [Fact]public void Negative_signed_margins_are_preserved_exactly(){var s=D("21-negative-margin.docx").Sections.Single();Assert.Equal(-120,s.MarginTopTwips);Assert.Equal(-240,s.MarginBottomTwips);}
 [Fact]public void Relationship_graph_contains_internal_and_external(){var h=D("08-header-footer.docx");Assert.Contains(h.Relationships,x=>!x.IsExternal&&x.Type.EndsWith("/header")&&x.SourcePart=="word/document.xml");var e=D("14-external-relationship.docx");Assert.Contains(e.Relationships,x=>x.IsExternal&&x.Type.EndsWith("/hyperlink"));Assert.Contains(e.Relationships,x=>!x.IsExternal&&x.Type.EndsWith("/styles"));}
 [Fact]public void Unsupported_feature_is_not_normal(){var x=PackageSafetyPreflight.Inspect(F("22-unsupported-altchunk.docx"));Assert.Contains("altChunk",x.UnsupportedFeatures);Assert.Equal(PatchPolicy.PROHIBITED,x.PatchPolicy);Assert.NotEmpty(x.Diagnostics);}

}
