using System.IO.Compression; using System.Xml.Linq; using Nd30.DocumentEngine.Model;
namespace Nd30.DocumentEngine.Safety;
public static class PackageSafetyPreflight {
 public static PackageSafetyState Inspect(string path){var d=new List<Diagnostic>();try{using var z=ZipFile.OpenRead(path);var names=z.Entries.Select(e=>e.FullName).ToHashSet(StringComparer.OrdinalIgnoreCase);if(!names.Contains("[Content_Types].xml")||!names.Contains("_rels/.rels")||!names.Contains("word/document.xml")){d.Add(new("OPC_REQUIRED_PART_MISSING","Required OPC/Word part missing."));return new(false,false,false,false,false,false,false,["invalid-opc"],PatchPolicy.PROHIBITED,d);}bool macros=names.Contains("word/vbaProject.bin");bool ole=names.Any(n=>n.StartsWith("word/embeddings/",StringComparison.OrdinalIgnoreCase));bool sig=names.Any(n=>n.StartsWith("_xmlsignatures/",StringComparison.OrdinalIgnoreCase));bool tracked=XmlContainsAny(z,"word/document.xml",["ins","del","moveFrom","moveTo"]);bool prot=HasProtection(z);bool ext=HasExternalRelationships(z);var unsupported=DetectUnsupported(z,names);if(names.Any(n=>n.EndsWith("encryptedPackage",StringComparison.OrdinalIgnoreCase)))unsupported.Add("encrypted-package");foreach(var u in unsupported)d.Add(new("UNSUPPORTED_FEATURE",$"Unsupported mutation-risk feature detected: {u}."));if(sig)d.Add(new("SIGNED_PACKAGE","OPC signature structure detected; cryptographic validity not verified."));if(macros)d.Add(new("MACRO_PRESENT","Macro project preserved but never executed."));if(ole)d.Add(new("OLE_PRESENT","Embedded/OLE object preserved but never executed."));if(tracked)d.Add(new("TRACKED_CHANGES_PRESENT","Tracked changes preserved; automatic mutation is audit-only."));if(ext)d.Add(new("EXTERNAL_RELATIONSHIP","External relationship requires guarded handling."));if(prot)d.Add(new("DOCUMENT_PROTECTED","Document protection detected."));var p=unsupported.Count>0?PatchPolicy.PROHIBITED:(sig||prot||macros||ole||tracked?PatchPolicy.AUDIT_ONLY:(ext?PatchPolicy.GUARDED:PatchPolicy.NORMAL));return new(true,sig,prot,macros,tracked,ole,ext,unsupported,p,d);}catch(Exception ex){d.Add(new("PACKAGE_UNREADABLE",ex.Message));return new(false,false,false,false,false,false,false,["unreadable-package"],PatchPolicy.PROHIBITED,d);}}
 static bool XmlContainsAny(ZipArchive z,string n,IEnumerable<string> locals){var e=z.GetEntry(n);if(e is null)return false;using var s=e.Open();var x=XDocument.Load(s);return x.Descendants().Any(q=>locals.Contains(q.Name.LocalName));}
 static bool HasProtection(ZipArchive z){var e=z.GetEntry("word/settings.xml");if(e is null)return false;using var s=e.Open();var x=XDocument.Load(s);return x.Descendants().Any(q=>q.Name.LocalName=="documentProtection");}
 static List<string> DetectUnsupported(ZipArchive z,HashSet<string> names){var u=new List<string>();if(XmlContainsAny(z,"word/document.xml",["altChunk"]))u.Add("altChunk");if(names.Any(n=>n.Contains("activeX",StringComparison.OrdinalIgnoreCase)))u.Add("activeX-control");foreach(var e in z.Entries.Where(e=>e.FullName.EndsWith(".rels",StringComparison.OrdinalIgnoreCase))){using var st=e.Open();var x=XDocument.Load(st);foreach(var r in x.Descendants().Where(q=>q.Name.LocalName=="Relationship")){var t=(string?)r.Attribute("Type")??"";var target=(string?)r.Attribute("Target")??"";if(t.Contains("attachedTemplate",StringComparison.OrdinalIgnoreCase))u.Add("attached-template");if(t.Contains("package",StringComparison.OrdinalIgnoreCase))u.Add("embedded-package");if(t.Contains("oleObject",StringComparison.OrdinalIgnoreCase)&&(string?)r.Attribute("TargetMode")=="External")u.Add("linked-ole");if(t.Contains("control",StringComparison.OrdinalIgnoreCase))u.Add("activex-control");}}return u.Distinct().ToList();}
 static bool HasExternalRelationships(ZipArchive z){foreach(var e in z.Entries.Where(e=>e.FullName.EndsWith(".rels",StringComparison.OrdinalIgnoreCase))){using var s=e.Open();var x=XDocument.Load(s);if(x.Descendants().Any(a=>a.Name.LocalName=="Relationship"&&(string?)a.Attribute("TargetMode")=="External"))return true;}return false;}
}
