import zipfile, pathlib
R=pathlib.Path('fixtures/docx'); R.mkdir(parents=True,exist_ok=True)
W='http://schemas.openxmlformats.org/wordprocessingml/2006/main'; RR='http://schemas.openxmlformats.org/officeDocument/2006/relationships'; PR='http://schemas.openxmlformats.org/package/2006/relationships'; CTNS='http://schemas.openxmlformats.org/package/2006/content-types'
TYPES={
 'word/document.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml','word/styles.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml','word/settings.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml','word/numbering.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml','word/header1.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml','word/header2.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml','word/header3.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml','word/footer1.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml','word/footer2.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml','word/footer3.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml','word/comments.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml','word/footnotes.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml','word/endnotes.xml':'application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml','word/vbaProject.bin':'application/vnd.ms-office.vbaProject','word/embeddings/oleObject1.bin':'application/vnd.openxmlformats-officedocument.oleObject','_xmlsignatures/origin.sigs':'application/vnd.openxmlformats-package.digital-signature-origin','_xmlsignatures/sig1.xml':'application/vnd.openxmlformats-package.digital-signature-xmlsignature+xml'}
def cts(parts,macro=False):
 o=[]
 for p in parts:
  if p=='word/document.xml' and macro: ct='application/vnd.ms-word.document.macroEnabled.main+xml'
  else: ct=TYPES.get(p)
  if ct:o.append(f'<Override PartName="/{p}" ContentType="{ct}"/>')
 return f'<?xml version="1.0"?><Types xmlns="{CTNS}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="html" ContentType="text/html"/><Default Extension="bin" ContentType="application/octet-stream"/>{"".join(o)}</Types>'
def mk(name,body,styles='',settings='',parts=None,rels='',macro=False,finalsect=None,rootextra=''):
 parts=dict(parts or {}); finalsect=finalsect or '<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1701"/></w:sectPr>'
 doc=f'<?xml version="1.0"?><w:document xmlns:w="{W}" xmlns:r="{RR}"><w:body>{body}{finalsect}</w:body></w:document>'
 st=f'<?xml version="1.0"?><w:styles xmlns:w="{W}"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman"/><w:sz w:val="28"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:jc w:val="both"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:styleId="Normal"><w:name w:val="Normal"/></w:style>{styles}</w:styles>'
 se=f'<?xml version="1.0"?><w:settings xmlns:w="{W}">{settings}</w:settings>'
 base={'word/document.xml':doc,'word/styles.xml':st,'word/settings.xml':se,'word/_rels/document.xml.rels':f'<?xml version="1.0"?><Relationships xmlns="{PR}"><Relationship Id="rStyles" Type="{RR}/styles" Target="styles.xml"/><Relationship Id="rSettings" Type="{RR}/settings" Target="settings.xml"/>{rels}</Relationships>'};base.update(parts)
 root=f'<?xml version="1.0"?><Relationships xmlns="{PR}"><Relationship Id="rId1" Type="{RR}/officeDocument" Target="word/document.xml"/>{rootextra}</Relationships>'
 with zipfile.ZipFile(R/name,'w',zipfile.ZIP_DEFLATED) as z:
  z.writestr('[Content_Types].xml',cts(base,macro));z.writestr('_rels/.rels',root)
  for k,v in base.items():z.writestr(k,v)
p=lambda text:f'<w:p><w:r><w:t>{text}</w:t></w:r></w:p>'
mk('01-simple.docx',p('Hello'))
mk('02-paragraph-style.docx','<w:p><w:pPr><w:pStyle w:val="Body"/></w:pPr><w:r><w:t>Styled</w:t></w:r></w:p>','<w:style w:type="paragraph" w:styleId="Body"><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:before="120"/></w:pPr><w:rPr><w:sz w:val="30"/></w:rPr></w:style>')
mk('03-inherited-style.docx','<w:p><w:pPr><w:pStyle w:val="Child"/></w:pPr><w:r><w:rPr><w:rStyle w:val="Emphasis"/></w:rPr><w:t>Inherited</w:t></w:r></w:p>','<w:style w:type="paragraph" w:styleId="Base"><w:rPr><w:b/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Child"><w:basedOn w:val="Base"/><w:rPr><w:color w:val="112233"/></w:rPr></w:style><w:style w:type="character" w:styleId="Emphasis"><w:rPr><w:i/></w:rPr></w:style>')
mk('04-direct-override.docx','<w:p><w:pPr><w:pStyle w:val="Body"/></w:pPr><w:r><w:rPr><w:b w:val="false"/><w:i/><w:sz w:val="32"/></w:rPr><w:t>Override</w:t></w:r></w:p>','<w:style w:type="paragraph" w:styleId="Body"><w:rPr><w:b/></w:rPr></w:style>')
sec1='<w:p><w:pPr><w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:right="800" w:bottom="1100" w:left="1600"/></w:sectPr></w:pPr><w:r><w:t>S1</w:t></w:r></w:p>'+p('S2')
mk('05-multi-section.docx',sec1,finalsect='<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1200" w:right="900" w:bottom="1300" w:left="1700"/></w:sectPr>')
land='<w:p><w:pPr><w:sectPr><w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/><w:pgMar w:top="900" w:right="700" w:bottom="1000" w:left="1500"/></w:sectPr></w:pPr><w:r><w:t>Landscape section</w:t></w:r></w:p>'+p('Portrait final')
mk('06-landscape-section.docx',land,finalsect='<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1701"/></w:sectPr>')
mk('07-table.docx','<w:tbl><w:tr><w:tc>'+p('Cell A')+'</w:tc><w:tc>'+p('Cell B')+'</w:tc></w:tr></w:tbl>')
hparts={}; rels=[]; refs=[]
for i,k in enumerate(('default','first','even'),1):
 hparts[f'word/header{i}.xml']=f'<w:hdr xmlns:w="{W}">'+p(f'Header {k}')+'</w:hdr>';hparts[f'word/footer{i}.xml']=f'<w:ftr xmlns:w="{W}">'+p(f'Footer {k}')+'</w:ftr>';rels += [f'<Relationship Id="rH{i}" Type="{RR}/header" Target="header{i}.xml"/>',f'<Relationship Id="rF{i}" Type="{RR}/footer" Target="footer{i}.xml"/>'];refs += [f'<w:headerReference w:type="{k}" r:id="rH{i}"/>',f'<w:footerReference w:type="{k}" r:id="rF{i}"/>']
mk('08-header-footer.docx',p('Body'),parts=hparts,rels=''.join(rels),settings='<w:evenAndOddHeaders/>',finalsect='<w:sectPr>'+''.join(refs)+'<w:titlePg/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1701"/></w:sectPr>')
fields='<w:p><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText> PAGE </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>3</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p><w:p><w:fldSimple w:instr=" NUMPAGES "><w:r><w:t>9</w:t></w:r></w:fldSimple></w:p>'
mk('09-page-numbering.docx',fields,finalsect='<w:sectPr><w:pgNumType w:start="3" w:fmt="decimal"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1701"/></w:sectPr>')
mk('10-tracked-changes.docx','<w:p><w:ins w:id="1" w:author="test"><w:r><w:t>Inserted</w:t></w:r></w:ins></w:p>')
mk('11-protected.docx',p('Protected'),settings='<w:documentProtection w:edit="readOnly" w:enforcement="1"/>')
mk('12-macro-enabled.docm',p('Macro preserved'),parts={'word/vbaProject.bin':b'DETERMINISTIC-NONEXECUTABLE-MACRO-FIXTURE'},rels=f'<Relationship Id="rVba" Type="{RR}/vbaProject" Target="vbaProject.bin"/>',macro=True)
mk('13-ole-embedded.docx','<w:p><w:r><w:object><w:objectEmbed r:id="rOle"/></w:object></w:r></w:p>',parts={'word/embeddings/oleObject1.bin':b'DETERMINISTIC-NONEXECUTABLE-OLE-FIXTURE'},rels=f'<Relationship Id="rOle" Type="{RR}/oleObject" Target="embeddings/oleObject1.bin"/>')
mk('14-external-relationship.docx',p('External'),rels=f'<Relationship Id="rExt" Type="{RR}/hyperlink" Target="https://example.invalid/" TargetMode="External"/>')
sigparts={'_xmlsignatures/origin.sigs':'','_xmlsignatures/_rels/origin.sigs.rels':f'<?xml version="1.0"?><Relationships xmlns="{PR}"><Relationship Id="rSig1" Type="http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/signature" Target="sig1.xml"/></Relationships>','_xmlsignatures/sig1.xml':'<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><Object>STRUCTURE-SIMULATION-NOT-CRYPTOGRAPHICALLY-VALID</Object></Signature>'}
mk('15-signed-structure-simulation.docx',p('Signed structure simulation'),parts=sigparts,rootextra='<Relationship Id="rSigOrigin" Type="http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/origin" Target="_xmlsignatures/origin.sigs"/>')
notes={'word/footnotes.xml':f'<w:footnotes xmlns:w="{W}"><w:footnote w:id="1">{p("Footnote")}</w:footnote></w:footnotes>','word/endnotes.xml':f'<w:endnotes xmlns:w="{W}"><w:endnote w:id="1">{p("Endnote")}</w:endnote></w:endnotes>','word/comments.xml':f'<w:comments xmlns:w="{W}"><w:comment w:id="0" w:author="test">{p("Comment")}</w:comment></w:comments>'}
nrels=f'<Relationship Id="rFoot" Type="{RR}/footnotes" Target="footnotes.xml"/><Relationship Id="rEnd" Type="{RR}/endnotes" Target="endnotes.xml"/><Relationship Id="rComments" Type="{RR}/comments" Target="comments.xml"/>'
mk('16-readonly-parts.docx','<w:p><w:commentRangeStart w:id="0"/><w:r><w:t>Annotated</w:t></w:r><w:commentRangeEnd w:id="0"/><w:r><w:commentReference w:id="0"/></w:r><w:r><w:footnoteReference w:id="1"/></w:r><w:r><w:endnoteReference w:id="1"/></w:r></w:p>',parts=notes,rels=nrels)
numbering=f'<w:numbering xmlns:w="{W}"><w:abstractNum w:abstractNumId="10"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl><w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="lowerLetter"/><w:lvlText w:val="%2)"/></w:lvl></w:abstractNum><w:num w:numId="42"><w:abstractNumId w:val="10"/></w:num></w:numbering>'
mk('17-numbering.docx','<w:p><w:pPr><w:numPr><w:ilvl w:val="1"/><w:numId w:val="42"/></w:numPr></w:pPr><w:r><w:t>Numbered</w:t></w:r></w:p>',parts={'word/numbering.xml':numbering},rels=f'<Relationship Id="rNum" Type="{RR}/numbering" Target="numbering.xml"/>')
vals=['',' w:val="true"',' w:val="1"',' w:val="false"',' w:val="0"']
body=p('absent')+''.join(f'<w:p><w:r><w:rPr><w:b{v}/><w:i{v}/></w:rPr><w:t>case{i}</w:t></w:r></w:p>' for i,v in enumerate(vals,1))
mk('18-onoff-semantics.docx',body)
mk('19-style-cycle.docx','<w:p><w:pPr><w:pStyle w:val="CycleA"/></w:pPr><w:r><w:t>Cycle</w:t></w:r></w:p>','<w:style w:type="paragraph" w:styleId="CycleA"><w:basedOn w:val="CycleB"/></w:style><w:style w:type="paragraph" w:styleId="CycleB"><w:basedOn w:val="CycleA"/></w:style>')
print('fixtures',len(list(R.glob('*.doc*'))))
spacing_styles='<w:style w:type="paragraph" w:styleId="SpacingBase"><w:pPr><w:spacing w:line="276" w:lineRule="auto"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="SpacingChild"><w:basedOn w:val="SpacingBase"/></w:style>'
spacing_body=''.join([f'<w:p><w:pPr><w:spacing w:line="{raw}" w:lineRule="{rule}"/></w:pPr><w:r><w:t>{label}</w:t></w:r></w:p>' for raw,rule,label in [('240','auto','auto1'),('276','auto','auto115'),('360','auto','auto15'),('240','exact','exact12'),('280','atLeast','atleast14')]])+'<w:p><w:pPr><w:pStyle w:val="SpacingChild"/></w:pPr><w:r><w:t>inherited</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="SpacingChild"/><w:spacing w:line="360" w:lineRule="auto"/></w:pPr><w:r><w:t>override</w:t></w:r></w:p>'
mk('20-line-spacing.docx',spacing_body,spacing_styles)
mk('21-negative-margin.docx',p('Negative margin'),finalsect='<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="-120" w:right="850" w:bottom="-240" w:left="1701"/></w:sectPr>')
mk('22-unsupported-altchunk.docx',p('Unsupported')+'<w:altChunk r:id="rAlt"/>',parts={'word/afchunk1.html':'<html><body>altChunk</body></html>'},rels=f'<Relationship Id="rAlt" Type="{RR}/aFChunk" Target="afchunk1.html"/>')
